config/routes.rb
Testapp::Application.routes.draw do
  resources :comments

  devise_for :users

  resources :articles

   root :to => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
belongs_to :user
has_many :comments
  attr_accessible :description, :title
  
  validates :title,  :presence => true
  validates :description,  :presence => true

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  attr_accessible :commentonarticle, :name
  validates :name,  :presence => true
  validates :commentonarticle,  :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
	
class ArticlesController < ApplicationController

before_filter :authenticate_user!, :except => [:index]

  # GET /articles
  # GET /articles.json
  def index
  #  @articles = Article.all.Kaminari.paginate_array(my_array_object).page(params[:page]).per(3)
myarray = Article.all
@articles = Kaminari.paginate_array(myarray).page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comment = Comment.find(params[:id])
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @user = current_user
    @article = @user.articles.create(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, :notice => 'Article was successfully created.' }
        format.json { render :json => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, :notice => 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @article = Article.find(params[:id])
    @comment = @article.comments.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @article = Article.find(params[:id])
    @comment = @article.comments.build(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_path(:id => @article.id), :notice => 'Comment was successfully created.' }
        format.json { render :json => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.json { render :json => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, :notice => 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
 
  <% if user_signed_in? %>
  <table border = 1><tr><th>name of article</th><th>description</th></tr>
		
		<% @articles.each do |article| %>		
				 <% if article.user_id  == current_user.id %>
					 <tr><td><%= article.title %></td>	
					 <td><%=h truncate(article.description, :length => 15) %>
						<%if article.description.length >= 15 %>
							<%= link_to "more", article %>
					   <%end%></td>
						<td> Comment: <%= link_to "comment", :controller => :comments, :action => :new, :id => article.id  %></td>	</tr>
				 <%end%>
		<%end%>
		
		</table><%= paginate @articles %>
	<br>	<%= link_to "create new article", new_article_path %>

  <%else%>

  <u>ALL LIST OF ARTICLS</u></br>
		<table border = 1><tr><th>article id</th><th>name of article</th><th>description</th></tr>
		<% @articles.each do |article| %>
					<tr>
					<td><%= article.id %></td>
					<td><%= article.title %></td>	
					<td><%=h truncate(article.description, :length => 15) %>
						<%if article.description.length >= 15 %>
							<%= link_to "more", article %>
					   <%end%></td>	
				 	</tr>
		<%end%>
		</table>
		  <%= paginate @articles %>
  <%end%>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Description:</b>
  <%= @article.description %>
</p>
 <% @article.comments.each do |comment| %>
		<%= comment.name%><br>
		<%= comment.commentonarticle %><hr>
    <%end%>
<%if current_user.id == @article.user_id%>
   
 <%= link_to 'Edit', edit_article_path(@article) %> 
	
<%end%>
Comment: <%= link_to "comment", :controller => :comments, :action => :new, :id => @article.id  %>

<%= link_to 'Back', articles_path %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Commentonarticle</th>
    <th>Article</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.commentonarticle %></td>
    <td><%= comment.article %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
(<%= link_to "back to create new article", new_article_path  %>)<br>
(<%=link_to "back to all comments for this article", article_path(:id => @article.id)%>)<br>
Title: <%= @article.title %>
Description: <%= @article.description %>
<%= form_for @comment, :url => {:action => :create, :id => @article.id} do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :commentonarticle %><br />
    <%= f.text_area :commentonarticle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', articles_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Commentonarticle:</b>
  <%= @comment.commentonarticle %>
</p>

<p>
  <b>Article:</b>
  <%= @comment.article %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>

<%= yield %>

</body>
</html>